AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM app supporting the Fantheon page'

Globals:
    Function:
        Timeout: 3


Resources:

    GetActorsFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: main/
            Handler: app.get_actors_for_franchise
            Runtime: python3.6
            Events:
                GetActors:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /get_actors_for_franchise
                        Method: get


Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for GetActorsForFranchise function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_actors_for_franchise/"
